name: Deploy cloud function

on:
  push:
    branches: ["cloudFunction"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:
    name: Deploy Cloud function
    uses: andrew-field/reusable-workflows/.github/workflows/deploy-cloud-function.yml@master
    with:
      function_name: pickCloudFunction2
    secrets: inherit